const http = require('http');
const fs = require('fs');
const nodemailer = require('nodemailer');

let transporter = nodemailer.createTransport({
    service: 'Mail.ru',
    port: 465,
    secure: true,
    auth: {
        user: 'buisnessbotsss@mail.ru',
        pass: 'hMGDtuYMXS3fVw537zeQ'
    }
})
let mailOptions = {
    from: 'mr.shchepetkin@gmail.com',
    to: 'zhao.94@mail.ru',
    subject: 'This message was generated by yung Trappa',
    text: 'Free Yung Thugga, Free Gunna, they aint did nothing'
}
transporter.sendMail(mailOptions, function (error, info) {
    if (error) {
        console.log(error);
    } else {
        console.log(info.response);
    }
})

http.createServer(function (req, res) {
    fs.readFile('index.html', function (err, data) {
        res.writeHead(200, {'Content-Type': 'text/html'});
        res.write(data);
        return res.end();
    });
}).listen(8080);